language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3

sudo: false

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction

script:
  - mkdir -p build/logs
  - ./vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_success:
  - php vendor/bin/coveralls -v

before_deploy:
  - php -d phar.readonly=false vendor/bin/box build && mv optimus.phar optimus

deploy:
  provider: releases
  api_key:
    secure: $GITHUB_TOKEN
  file_glob: true
  file:
    - optimus
  skip_cleanup: true
  on:
    tags: true
