name: tests

on:
  push:
  pull_request:

jobs:
  test:

    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        php: [7.4, 8.0, 8.1]
        composer-flag: [prefer-lowest, prefer-stable]

    name: php v${{ matrix.php }} - ${{ matrix.composer-flag }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pdo, bcmath, gmp
          tools: composer:v2

      - name: Install dependencies
        run: composer update --${{ matrix.composer-flag }} --no-interaction --no-progress

      - name: Execute tests and submit coverage
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mkdir -p build/logs
          composer test -- --coverage-clover build/logs/clover.xml
          composer require --dev -n "php-coveralls/php-coveralls":"^2.5.2"
          ./vendor/bin/php-coveralls -v 
